/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/Jail.glb -o src/components/Jail.jsx 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Jail(props) {
  const { nodes, materials } = useGLTF('/models/Jail.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.jail.geometry} material={materials.Cell} />
    </group>
  )
}

useGLTF.preload('/models/Jail.glb')
